#!/usr/bin/env node
/**
 * generate-index.js — Auto-generate FUNCTION_INDEX.md from source files
 * 
 * Usage:  node generate-index.js
 * Output: FUNCTION_INDEX.md in the same directory
 * 
 * วิธีใช้: เปิด CMD ใน folder repo แล้วรัน node generate-index.js
 */

const fs = require('fs');
const path = require('path');

const REPO_DIR = __dirname;
const OUTPUT = path.join(REPO_DIR, 'FUNCTION_INDEX.md');

// Files to scan (order = display order)
const SOURCE_FILES = fs.readdirSync(REPO_DIR)
  .filter(f => f.endsWith('.js') || f.endsWith('.html'))
  .filter(f => f !== 'generate-index.js')  // skip self
  .sort((a, b) => {
    // code.js first, then alphabetical
    if (a === 'code.js') return -1;
    if (b === 'code.js') return 1;
    return a.localeCompare(b);
  });

function extractFunctions(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const results = [];
  
  lines.forEach((line, idx) => {
    // Match: function name(  or  function name (
    const match = line.match(/^(?:\/\/.*)?(?:function\s+)(\w+)\s*\(/);
    if (match) {
      results.push({
        line: idx + 1,
        name: match[1],
        // Grab preceding comment if exists
        comment: (idx > 0 && lines[idx-1].trim().startsWith('//')) 
          ? lines[idx-1].trim().replace(/^\/\/\s*/, '') 
          : ''
      });
    }
  });
  
  return results;
}

function getLineCount(filePath) {
  return fs.readFileSync(filePath, 'utf8').split('\n').length;
}

// Build markdown
const now = new Date().toISOString().split('T')[0];
let md = `# Siriraj Rx Shift — Function Index (auto-generated)\n\n`;
md += `**Generated:** ${now} | **Files:** ${SOURCE_FILES.length}\n\n`;
md += `> Auto-generated by \`node generate-index.js\`\n`;
md += `> ค้นหาด้วย Ctrl+F ในไฟล์นี้\n\n`;
md += `---\n\n`;

let totalFunctions = 0;

SOURCE_FILES.forEach(file => {
  const filePath = path.join(REPO_DIR, file);
  const funcs = extractFunctions(filePath);
  const lineCount = getLineCount(filePath);
  
  if (funcs.length === 0 && !file.endsWith('.html')) return;
  
  totalFunctions += funcs.length;
  
  md += `## ${file} (~${lineCount} lines)\n\n`;
  
  if (funcs.length === 0) {
    md += `*(No exported functions — UI/markup file)*\n\n`;
    md += `---\n\n`;
    return;
  }
  
  md += `| Line | Function | Comment |\n`;
  md += `|------|----------|---------|\n`;
  
  funcs.forEach(f => {
    const icon = f.name.startsWith('test') || f.name.startsWith('debug') ? '🧪' 
               : f.name.startsWith('dev') ? '🔧'
               : '';
    md += `| ${f.line} | \`${f.name}\` ${icon} | ${f.comment} |\n`;
  });
  
  md += `\n---\n\n`;
});

// Summary at top
const summary = `**Total functions:** ${totalFunctions}\n\n`;
md = md.replace('---\n\n', '---\n\n' + summary);

fs.writeFileSync(OUTPUT, md, 'utf8');
console.log(`Done! ${totalFunctions} functions from ${SOURCE_FILES.length} files -> FUNCTION_INDEX.md`);
